title: PowerQuery M Reference Guide
description: A community-run reference guide for the PowerQuery M language.
baseurl: /pqm-guide/

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

destination: docs
incremental: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
  - build.bat
  - build.sh
  - serve.bat
  - serve.sh
  - shell.bat
  - shell.sh
  - create_function_pages.py
  - power_m_functions.txt