title: PowerQuery M Reference Guide
description: A community-run reference guide for the PowerQuery M language.

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

destination: docs

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
